
server:
  port: 8081

openWeather:
  api:
    url: https://api.openweathermap.org/data/2.5/forecast?q={q}&appid={appid}&cnt={cnt}&units={units}
    key: "d2929e9483efc82c82c32ee7e02d563e"

weather:
  forecast:
    min: 1
    max: 4

ops:
  retry:
    max:
      attempts: 4
    initial:
      interval: 1000
    interval:
      multiplier: 3