
server:
  port: 8081

openWeather:
  api:
    url: https://api.openweathermap.org/data/2.5/forecast?q={q}&appid={appid}&cnt={cnt}&units={units}
    key: "d2929e9483efc82c82c32ee7e02d563e"

spring:
  application:
    name: forecast-weather-application
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-27176195.okta.com/oauth2/default
        client:
          registration:
            internal-client:
              provider: okta
              authorization-grant-type: client_credentials
              scope: internal
              client-id: 0oaa8svkacCTWWaGm5d7
              client-secret: lmy5OuSW4BXsb2i_mDnBU5NCxlpaS1G0Hpj_QsjR
          provider:
            okta:
              issuer-uri: https://dev-27176195.okta.com/oauth2/default

weather:
  forecast:
    min: 1
    max: 4

ops:
  retry:
    max:
      attempts: 4
    initial:
      interval: 1000
    interval:
      multiplier: 3

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-27176195.okta.com/oauth2/default
    audience: api://default