apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-weather-application
spec:
  selector:
    matchLabels:
      app: forecast-weather-application
  template:
    metadata:
      labels:
        app: forecast-weather-application
    spec:
      containers:
      - name: forecast-weather-application
        image: IMAGE_URL/forecastweatherapplication
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
